server:
  port: 8081

spring:
  application:
    name: produto-service
  datasource:
    url: jdbc:postgresql://localhost:5436/produtos
    username: docker
    password: docker
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    addresses: ${SPRING_RABBITMQ_ADDRESSES:localhost:5672}
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:admin}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
