spring:
  application:
    name: cozinha

  rabbitmq:
    port: 5672
    addresses: ${SPRING_RABBITMQ_ADDRESSES:localhost:5672}
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:admin}
    listener:
      simple:
        concurrency: 1
        max-concurrency: 1
        prefetch: 1
        acknowledge-mode: auto
        retry:
          enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: 9090
